services:
  namer:
    image: ghcr.io/rzp-labs/namer:1.19.18
    container_name: namer
    restart: unless-stopped
    networks:
      - rzp-net
    ports:
      - 6980:6980
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    group_add:
      - "18"  # video group for GPU access
    volumes:
      - /mnt/user/appdata/namer/config:/app/config
      - /mnt/user/appdata/namer/database:/app/database
      - /mnt/user/appdata/namer/logs:/app/logs
      - /mnt/user/data/media/namer:/app/media
    environment:
      - NAMER_CONFIG=/app/config/namer-prod.cfg
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - LIBVA_DRIVER_NAME=iHD
      - TPDB_TOKEN=${TPDB_TOKEN}
      - STASHDB_TOKEN=${STASHDB_TOKEN}
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:6980/api/healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - com.centurylinklabs.watchtower.enable=true
  # Backlog instance - for processing existing files
  namer-backlog:
    image: ghcr.io/rzp-labs/namer:1.19.18
    container_name: namer-backlog
    restart: unless-stopped
    networks:
      - rzp-net
    ports:
      - 6982:6980
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    group_add:
      - "18"  # video group for GPU access
    volumes:
      - /mnt/user/appdata/namer-backlog/config:/app/config
      - /mnt/user/appdata/namer-backlog/database:/app/database
      - /mnt/user/appdata/namer-backlog/logs:/app/logs
      - /mnt/user/data/media/namer-backlog:/app/media
    environment:
      - NAMER_CONFIG=/app/config/namer-backlog.cfg
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - LIBVA_DRIVER_NAME=iHD
      - TPDB_TOKEN=${TPDB_TOKEN}
      - STASHDB_TOKEN=${STASHDB_TOKEN}
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:6980/api/healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - com.centurylinklabs.watchtower.enable=true
  # Auto-updater - checks for new images every hour
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 3 * * * # Check daily at 3am
      - TZ=America/Phoenix
networks:
  rzp-net:
    external: true
