services:
  namer:
    image: nehpz/namer:latest
    container_name: namer
    restart: unless-stopped
    
    # Intel GPU hardware acceleration support
    # devices:
    #   - /dev/dri:/dev/dri
    
    # Volume mounts
    volumes:
      - ./test/integration/config:/app/config
      - ./test/integration/database:/app/database
      - ./test/integration/logs:/app/logs
      - ./test/integration/media:/app/media
    
    # Port mapping
    ports:
      - "6980:6980"
    
    # Environment variables for Intel GPU support and user management
    environment:
      - NAMER_CONFIG=/app/config/namer.cfg
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      # - LIBVA_DRIVER_NAME=${LIBVA_DRIVER_NAME:-iHD}
      - TPDB_TOKEN=${TPDB_TOKEN}
      - STASHDB_TOKEN=${STASHDB_TOKEN}
      - DEBUG=false
      # Uncomment below for GPU debugging
      # - DEBUG=true
      # - TEST_GPU=true
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:6980/api/healthcheck"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s

# Alternative configuration for pre-built image
# If you want to use a pre-built image instead of building locally,
# replace the 'build:' section above with:
#
# image: your-registry/namer:intel-gpu
#
# and remove the 'build:' section entirely.
