version: '3.8'

services:
  namer:
    image: ghcr.io/rzp-labs/namer:latest
    container_name: namer
    restart: unless-stopped
    networks:
      - rzp-net
    ports:
      - 6980:6980
    volumes:
      - /mnt/user/appdata/namer/config:/config
      - /mnt/cache/data/media/downloads/complete:/media/downloads
      - /mnt/cache/data/media/namer/1-watch:/media/watch
      - /mnt/cache/data/media/namer/2-work:/media/work
      - /mnt/cache/data/media/namer/3-import:/media/processed
      - /mnt/cache/data/media/namer/4-failed:/failed
      - /mnt/user/appdata/namer/logs:/logs
    environment:
      - NAMER_CONFIG=/config/namer.cfg
      - TZ=${TZ:-America/Phoenix}
      - PUID=${PUID:-99}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-000}
      - LIBVA_DRIVER_NAME=${LIBVA_DRIVER_NAME:-iHD}
      - STASHDB_API_KEY=${STASHDB_API_KEY}
      - STASHDB_ENDPOINT=${STASHDB_ENDPOINT:-https://stashdb.org/graphql}
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:6980/api/healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # Backlog instance - for processing existing files
  namer-backlog:
    image: ghcr.io/rzp-labs/namer:latest
    container_name: namer-backlog
    restart: unless-stopped
    networks:
      - rzp-net
    ports:
      - 6981:6980
    volumes:
      - /mnt/user/appdata/namer-backlog/config:/config
      - /mnt/user/data/media/namer-backlog/0-intake:/media/intake
      - /mnt/user/data/media/namer-backlog/1-watch:/media/watch
      - /mnt/user/data/media/namer-backlog/2-work:/media/work
      - /mnt/user/data/media/namer-backlog/3-import:/media/processed
      - /mnt/user/data/media/namer-backlog/4-failed:/failed
      - /mnt/user/appdata/namer-backlog/logs:/logs
    environment:
      - NAMER_CONFIG=/config/namer.cfg
      - TZ=${TZ:-America/Phoenix}
      - PUID=${PUID:-99}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-000}
      - LIBVA_DRIVER_NAME=${LIBVA_DRIVER_NAME:-iHD}
      - STASHDB_API_KEY=${STASHDB_API_KEY}
      - STASHDB_ENDPOINT=${STASHDB_ENDPOINT:-https://stashdb.org/graphql}
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:6980/api/healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # Auto-updater - checks for new images every hour
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 3 * * *  # Check daily at 3am
      - TZ=${TZ:-America/Phoenix}
    command: --interval 86400 --cleanup --label-enable

networks:
  rzp-net:
    external: true
