name: PR Validation

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: pr-validate-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Lint and Test (Poetry)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # actions/checkout@v4 pinned to commit SHA
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 1

      - name: Set up Python
        # actions/setup-python@v5 pinned to commit SHA
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Install system ffmpeg
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg

      - name: Cache Poetry
        # actions/cache@v4 pinned to commit SHA
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install dependencies
        run: |
          poetry --version
          poetry install

      - name: Ruff check
        run: poetry run ruff check .

      - name: Pytest with coverage (skip slow)
        run: poetry run pytest -m "not slow" --cov --junitxml=pytest-junit.xml --cov-report=xml

      - name: Upload coverage.xml
        if: always()
        # actions/upload-artifact@v4 pinned to commit SHA
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Upload junit report
        if: always()
        # actions/upload-artifact@v4 pinned to commit SHA
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: pytest-junit
          path: pytest-junit.xml

  smoke:
    name: Build (amd64) and healthcheck container
    runs-on: ubuntu-latest
    needs: validate
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        # actions/checkout@v4 pinned to commit SHA
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        # docker/setup-buildx-action@v3 pinned to commit SHA
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Build image (amd64, load locally)
        # docker/build-push-action@v6 pinned to commit SHA
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          platforms: linux/amd64
          tags: nehpz/namer:pr-${{ github.sha }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start container
        run: |
          docker run -d --name namer \
            -e NAMER_CONFIG=/config/namer.cfg \
            -p 6980:6980 \
            -v "${{ github.workspace }}/config:/config:ro" \
            nehpz/namer:pr-${{ github.sha }}
          # Give it a moment to start
          sleep 15

      - name: Healthcheck
        run: |
          curl -sf http://127.0.0.1:6980/api/healthcheck

      - name: Dump logs on failure
        if: failure()
        run: |
          docker logs namer || true

      - name: Cleanup
        if: always()
        run: |
          docker rm -f namer || true
